#!/bin/bash

clear
echo "=== INSTALL PROTECT PANEL PTERODACTYL ==="
echo "Mulai menjalankan semua proteksi..."

repo="https://raw.githubusercontent.com/WAHIDOFC2/AntiRusuhh/main"
scripts=(
  "mbut.sh"
  "mbut2.sh"
  "mbut3.sh"
  "mbut4.sh"
  "mbut5.sh"
  "mbut6.sh"
  "mbut7.sh"
  "mbut8.sh"
  "mbut9.sh"
)

count=1
total=${#scripts[@]}

for script in "${scripts[@]}"; do
    echo ""
    echo "[$count/$total] Menjalankan $script ..."
    echo ""

    if curl -fsSL "$repo/$script" | bash; then
        echo "✔ $script selesai dijalankan"
    else
        echo "✖ Gagal menjalankan $script"
    fi

    count=$((count+1))
done

echo ""
echo "=== SEMUA PROTECT PANEL SUDAH SELESAI ==="
